spring:
  application:
    name: main-service
server:
  port: 5551

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  level:
    com.netflix: warn
